application: sanskrut-dev
version: 10
runtime: python27
api_version: 1
threadsafe: true

handlers: 

- url: /
  static_files: client_info.html
  upload: client_info.html
  secure: always

- url: /chatService
  static_files: home.html
  upload: home.html
  secure: always

- url: /max
  static_files: connectingCard.html
  upload: connectingCard.html

- url: /js
  static_dir: static/js
  secure: always
  
- url: /images
  static_dir: static/images

- url: /templates
  static_dir: static/templates

- url: /style
  static_dir: static/style

- url: /libs
  static_dir: static/libs
  secure: always

- url: /_ah/api/.*
  script: apis.main.init

builtins:
- deferred: on
- remote_api: on

libraries:
- name: ssl
  version: "2.7"

# - name: endpoints
#   version: 2.0

env_variables:
   # Replace with your endpoints service name.
   ENDPOINTS_SERVICE_NAME: sanskrut-dev.appspot.com
   # Replace with the version Id of your uploaded Endpoints service.
   ENDPOINTS_SERVICE_VERSION: 2017-08-19r1