application: sanskrut-dev
version: chat1
runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: chat.html
  upload: chat.html
  secure: always

- url: /static/js
  static_dir: static/js
  secure: always
  
- url: /images
  static_dir: static/images
  
- url: /libs
  static_dir: static/libs
  secure: always
- url: /style
  static_dir: static/style
